//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Educativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiantes()
        {
            this.EstudiantesMaterias = new HashSet<EstudiantesMaterias>();
        }
    
        public int EstudianteID { get; set; }
        public string EstudianteNombre { get; set; }
        public string EstudianteApellido { get; set; }
        public string EstudianteDireccion { get; set; }
        public string EstudianteTelefono { get; set; }
        public string EstudianteCorreo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public int CursoID { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudiantesMaterias> EstudiantesMaterias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
