//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Educativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesoresCursos
    {
        public int ProfesorCursoID { get; set; }
        public int ProfesorID { get; set; }
        public int CursoID { get; set; }
    
        public virtual Cursos Cursos { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}
