//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Centro_Educativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesores()
        {
            this.ProfesoresCursos = new HashSet<ProfesoresCursos>();
        }
    
        public int ProfesorID { get; set; }
        public string ProfesorNombre { get; set; }
        public string ProfesorApellido { get; set; }
        public string ProfesorTelefono { get; set; }
        public string ProfesorCedula { get; set; }
        public string ProfesorCorreo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public int MateriaID { get; set; }
    
        public virtual Materias Materias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesoresCursos> ProfesoresCursos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
